-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }
-keep class com.google.android.odml.** { *; }
-keep class com.google.android.datatransport.** { *; }
-dontwarn com.google.mlkit.**
